<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$title = 'Mes Livres';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('book', array('action'=>'add'));?>">Add new book</a>
 </p>

 <table class="table">
 <tr>
     <th>Titre</th>
     <th>Auteur</th>
     <th>Genre</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($books as $book) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($book->Titre);?></td>
     <td><?php echo $this->escapeHtml($book->Auteur);?></td>
     <td><?php echo $this->escapeHtml($book->Genre);?></td>
     <td>
         <a href="<?php echo $this->url('book',
             array('action'=>'edit', 'id' => $book->id));?>">Edit</a>
         <a href="<?php echo $this->url('book',
             array('action'=>'delete', 'id' => $book->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
